import Head from 'next/head';
import { Inter } from 'next/font/google';
import { withSSRContext } from 'aws-amplify';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Next Amplify SSR Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${inter.className} container`}>
        <ul className="list-group">
          {posts?.map((post) => (
            <li className="list-group-item" key={post.id}>
              {post.title}
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}

export async function getServerSideProps({ req }) {
  const SSR = withSSRContext({ req });
  const res = await SSR.API.get('postApi', '/posts');
  return {
    props: {
      posts: res.data,
    },
  };
}
